import { StrictMode, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import { COST_CATEGORIES, calculateScenarios, type CostCategory, type UserScenarioInput } from './calculations'
import { clearDraft, loadDraft, saveDraft, type SavedScenarioV1 } from './persistence'
import { loadApprovedPriceSuggestions, loadModeledPriceSuggestions, suggestionsForCrop, type PriceSuggestion, type PriceSuggestionsSnapshot } from './priceSuggestions'

const crops = [
  ['maize-white', 'White maize', 'dry grain'], ['rice', 'Rice', 'paddy'], ['cassava', 'Cassava', 'fresh roots'], ['yam', 'Yam', 'fresh tuber'], ['sorghum', 'Sorghum', 'dry grain'], ['rice-milled', 'Milled rice', 'milled rice'], ['gari-white', 'White gari', 'processed cassava'], ['millet', 'Pearl millet', 'dry grain'],
] as const
const labels: Record<CostCategory, string> = { land_preparation: 'Land prep', seed: 'Seed', fertilizer: 'Fertilizer', pesticide: 'Pesticide', labour: 'Labour', irrigation: 'Irrigation', transport: 'Transport', storage: 'Storage' }
type DraftCrop = SavedScenarioV1['inputsByCropId'][string]
const blankCrop = (): DraftCrop => ({ yieldTPerHa: '', sellingPriceNgnPerKg: '', lowPriceNgnPerKg: '', highPriceNgnPerKg: '', costsPerHa: Object.fromEntries(COST_CATEGORIES.map((key) => [key, ''])) as Record<CostCategory, string> })
const money = (value: number) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format(value)
const number = (value: string) => value.trim() === '' ? Number.NaN : Number(value)
const priceLabel = (draft: DraftCrop) => draft.priceOrigin === 'sourced_suggestion' && draft.priceSuggestion ? draft.priceSuggestion.priceType === 'modeled_estimate' ? `Modeled estimate · ${draft.priceSuggestion.marketName} · not observed` : `Sourced suggestion · ${draft.priceSuggestion.marketName} · ${draft.priceSuggestion.priceType}` : 'User-entered value'

function App() {
  const [restored] = useState(() => loadDraft()); const initial = restored.draft
  // A saved draft can mention a crop that no longer ships with the calculator.
  // Keep its inputs on disk for recovery, but never select an unavailable crop.
  const initialSelected = initial
    ? initial.selectedCropIds.filter((id) => crops.some((crop) => crop[0] === id))
    : ['maize-white', 'rice']
  const [area, setArea] = useState(initial?.areaHa ?? '')
  const [selected, setSelected] = useState<string[]>(initialSelected)
  const [inputs, setInputs] = useState<Record<string, DraftCrop>>(initial?.inputsByCropId ?? {})
  const [activeCrop, setActiveCrop] = useState(initialSelected[0] ?? '')
  const [priceSnapshot, setPriceSnapshot] = useState<PriceSuggestionsSnapshot>()
  const [suggestionsLoaded, setSuggestionsLoaded] = useState(false)
  const [notice, setNotice] = useState(restored.recovered ? 'Your saved draft could not be read, so a blank calculator was opened.' : restored.storageUnavailable ? 'This browser blocked local storage. Your changes will not survive a reload.' : '')
  const skipInitialSave = useRef(restored.recovered || restored.storageUnavailable)
  const getCrop = (id: string) => crops.find((crop) => crop[0] === id)!
  const draftFor = (id: string) => inputs[id] ?? blankCrop()
  useEffect(() => { loadApprovedPriceSuggestions().then((snapshot) => snapshot ?? loadModeledPriceSuggestions()).then((snapshot) => { setPriceSnapshot(snapshot); setSuggestionsLoaded(true) }) }, [])
  useEffect(() => {
    if (skipInitialSave.current) { skipInitialSave.current = false; return }
    const blank = area.trim() === '' && selected.length === 0 && Object.keys(inputs).length === 0
    if (blank) {
      if (!clearDraft()) setNotice('Your browser could not clear the saved draft.')
    } else if (!saveDraft({ areaHa: area, selectedCropIds: selected, inputsByCropId: inputs })) {
      setNotice('Your browser could not save this draft. Keep a copy of your figures before leaving.')
    }
  }, [area, selected, inputs])
  const batch = useMemo(() => calculateScenarios(selected.map((id) => { const crop = getCrop(id); const draft = draftFor(id); return { crop: { crop_id: crop[0], name: crop[1], form: crop[2] }, areaHa: number(area), yieldTPerHa: number(draft.yieldTPerHa), sellingPriceNgnPerKg: number(draft.sellingPriceNgnPerKg), ...(draft.lowPriceNgnPerKg || draft.highPriceNgnPerKg ? { priceRangeNgnPerKg: { low: number(draft.lowPriceNgnPerKg ?? ''), high: number(draft.highPriceNgnPerKg ?? '') } } : {}), costsPerHa: Object.fromEntries(COST_CATEGORIES.map((key) => [key, number(draft.costsPerHa[key])])) as Record<CostCategory, number> } as UserScenarioInput })), [area, selected, inputs])
  const update = (id: string, patch: Partial<DraftCrop>) => setInputs((current) => ({ ...current, [id]: { ...draftFor(id), ...patch } }))
  const updateCost = (id: string, key: CostCategory, value: string) => update(id, { costsPerHa: { ...draftFor(id).costsPerHa, [key]: value } })
  const applySuggestion = (id: string, suggestion: PriceSuggestion) => update(id, { marketId: suggestion.market_id, sellingPriceNgnPerKg: String(suggestion.value_ngn_per_kg), priceOrigin: 'sourced_suggestion', priceSuggestion: { snapshotId: priceSnapshot!.snapshot_id, suggestionId: suggestion.suggestion_id, marketId: suggestion.market_id, marketName: suggestion.market_name, priceType: suggestion.price_type, observationDate: suggestion.observation_date, sourceAttribution: suggestion.source.attribution } })
  const chooseSuggestion = (id: string, suggestionId: string) => {
    if (!suggestionId) { update(id, { marketId: '' }); return }
    const suggestion = suggestionsForCrop(priceSnapshot, id).find((item) => item.suggestion_id === suggestionId)
    if (suggestion) applySuggestion(id, suggestion)
  }
  const enterPrice = (id: string, sellingPriceNgnPerKg: string) => update(id, { sellingPriceNgnPerKg, priceOrigin: 'user_entered' })
  const toggle = (id: string) => { setSelected((current) => { const next = current.includes(id) ? current.filter((item) => item !== id) : [...current, id]; if (id === activeCrop && !next.includes(id)) setActiveCrop(next[0] ?? ''); return next }); if (!selected.includes(id)) setActiveCrop(id) }
  const ready = batch.status === 'ready'; const winner = ready ? batch.results[0] : undefined; const active = draftFor(activeCrop); const activeSuggestions = suggestionsForCrop(priceSnapshot, activeCrop)
  const reset = () => { const cleared = clearDraft(); setArea(''); setSelected([]); setInputs({}); setActiveCrop(''); setNotice(cleared ? 'Draft cleared. Enter at least two complete crop scenarios to compare.' : 'Your browser could not clear the saved draft. The screen was reset, but saved data may remain.') }
   return <div className="app-shell">
     {priceSnapshot?.lane === 'world-bank-modeled-estimates' && <div className="notice" role="status"><span>!</span><span>Optional modeled estimates are shown as editable context only. They are not observed retail, wholesale, or farmer selling prices.</span></div>}
    <header className="topbar"><div className="wordmark"><span className="leaf-mark">✳</span><span>fieldmargin</span></div><div className="status-chip"><span className="pulse" /> calculator-only · works offline</div><button className="icon-button" aria-label="Open help">?</button></header>
    <main><section className="hero"><div><p className="eyebrow">A calmer way to plan a season</p><h1>Know your margin<br /><em>before</em> you plant.</h1><p className="hero-copy">Compare crops using your own field numbers. Your draft stays on this device.</p></div><div className="hero-note"><span className="note-label">FIELD NOTE 01</span><strong>Profit is a scenario,<br />not a promise.</strong><span>Enter a selling point, yield, and local costs for each crop.</span></div></section>
      {notice && <div className="notice" role="status"><span>ⓘ</span><span>{notice}</span><button onClick={() => setNotice('')}>Dismiss</button></div>}
      <section className="workspace-grid"><aside className="control-panel"><div className="step-head"><span className="step-number">01</span><div><p className="eyebrow">Your field</p><h2>Set the scene</h2></div></div><label className="field-label">How much land?</label><div className="input-with-unit"><input aria-label="Area in hectares" type="number" min="0" step="0.1" value={area} onChange={(e) => setArea(e.target.value)} /><span>hectares</span></div><div className="step-head crop-step"><span className="step-number">02</span><div><p className="eyebrow">Your shortlist</p><h2>Pick crops to compare</h2></div></div><div className="crop-list">{crops.map((crop) => <label className={`crop-option ${selected.includes(crop[0]) ? 'is-selected' : ''}`} key={crop[0]}><input type="checkbox" checked={selected.includes(crop[0])} onChange={() => toggle(crop[0])} /><span className="crop-dot" /><span><strong>{crop[1]}</strong><small>{crop[2]}</small></span><span className="checkmark">✓</span></label>)}</div><p className="selection-hint">{selected.length} selected · compare at least 2</p><button className="text-button" onClick={reset}>Clear saved draft</button></aside>
        <section className="results-panel"><div className="results-head"><div><p className="eyebrow">03 / Decision view</p><h2>Your field margin</h2></div><button className="outline-button" disabled={!ready} onClick={() => window.print()}>Print report <span>↗</span></button></div>{winner ? <div className="recommendation"><div className="recommendation-tag">HIGHEST POINT SCENARIO</div><div className="recommendation-main"><div><h3>{winner.crop.name}</h3><p>{money(winner.profit)} estimated net profit on {area} ha</p></div><div className="recommendation-orbit"><span>₦</span></div></div><div className="recommendation-meta"><span>{priceLabel(draftFor(winner.crop.crop_id))} · point selling price</span><span>{winner.lowProfit !== undefined ? `range ${money(winner.lowProfit)} – ${money(winner.highProfit!)}` : 'No price range entered'}</span></div></div> : <div className="notice"><span>ⓘ</span><div>{batch.errors.length ? batch.errors.map((error, index) => <p key={`${error.cropId}-${error.field}-${index}`}>{error.cropId ? `${getCrop(error.cropId)[1]}: ` : ''}{error.message}</p>) : <p>Complete every field for every selected crop.</p>}</div></div>}<div className="result-toolbar"><div><h3>Compare your shortlist</h3><p>{ready ? 'Ranked by estimated net profit from your entered scenarios.' : 'Ranking appears only when every selected crop is complete.'}</p></div></div><div className="comparison-list">{ready && batch.results.map((result, index) => <article className={`result-card ${index === 0 ? 'top-result' : ''}`} key={result.crop.crop_id}><div className="rank">{String(index + 1).padStart(2, '0')}</div><div className="result-name"><strong>{result.crop.name}</strong><span>{priceLabel(draftFor(result.crop.crop_id))}</span></div><div className="result-numbers"><span><small>NET PROFIT</small><strong>{money(result.profit)}</strong></span><span><small>REVENUE</small><strong>{money(result.revenue)}</strong></span><span><small>ALL-IN COST</small><strong>{money(result.totalCost)}</strong></span></div><div className="profit-bar"><span style={{ width: `${Math.max(8, Math.min(100, result.profit / Math.max(1, batch.results[0].profit) * 100))}%` }} /></div><button className="edit-button" onClick={() => setActiveCrop(result.crop.crop_id)}>edit</button></article>)}</div>{ready && <div className="assumptions"><div><span className="assumption-icon">⌁</span><span><strong>How to read this</strong><br />Figures use your scenario inputs. Any supplied market price remains editable; nothing here is a forecast or guarantee.</span></div><div className="assumption-source">Basis: NGN, hectares, tonnes/ha, NGN/kg</div></div>}</section></section>
      <section className="editor-card"><div className="editor-head"><div><p className="eyebrow">Make it yours</p><h2>Enter assumptions</h2></div>{selected.length ? <select aria-label="Crop being edited" value={activeCrop} onChange={(e) => setActiveCrop(e.target.value)}>{selected.map((id) => <option key={id} value={id}>{getCrop(id)[1]}</option>)}</select> : <p role="status">Select a crop above to enter assumptions.</p>}</div>{selected.length > 0 && <div className="editor-grid"><div><label className="field-label" htmlFor="yield-input">Yield <span>tonnes / ha</span></label><input id="yield-input" className="line-input" aria-label="Yield tonnes per hectare" type="number" min="0" step="0.1" value={active.yieldTPerHa} onChange={(e) => update(activeCrop, { yieldTPerHa: e.target.value })} /><label className="field-label" htmlFor="market-input">Covered market <span>optional price prefill</span></label><select id="market-input" aria-label="Covered market" value={active.priceSuggestion?.suggestionId ?? ''} disabled={!activeSuggestions.length} onChange={(e) => chooseSuggestion(activeCrop, e.target.value)}><option value="">{suggestionsLoaded ? 'Choose a covered market' : 'Checking approved price snapshot…'}</option>{activeSuggestions.map((suggestion) => <option key={suggestion.suggestion_id} value={suggestion.suggestion_id}>{suggestion.market_name} · {suggestion.price_type}</option>)}</select><p className="field-hint">{activeSuggestions.length ? 'Selecting a market and price type fills the latest qualified price. You can change it.' : suggestionsLoaded ? 'No approved price suggestion for this crop. Enter your own selling price.' : 'Selling price stays manual until an approved local snapshot is available.'}</p><label className="field-label" htmlFor="price-input">Selling price <span>NGN / kg</span></label><input id="price-input" className="line-input" aria-label="Selling price NGN per kg" type="number" min="0" value={active.sellingPriceNgnPerKg} onChange={(e) => enterPrice(activeCrop, e.target.value)} /><p className="field-hint">{priceLabel(active)}</p><div className="range-fields"><label htmlFor="low-price">Low price<input id="low-price" aria-label="Low price" type="number" value={active.lowPriceNgnPerKg ?? ''} onChange={(e) => update(activeCrop, { lowPriceNgnPerKg: e.target.value })} /></label><label htmlFor="high-price">High price<input id="high-price" aria-label="High price" type="number" value={active.highPriceNgnPerKg ?? ''} onChange={(e) => update(activeCrop, { highPriceNgnPerKg: e.target.value })} /></label></div></div><div className="cost-editor"><label className="field-label">Production costs <span>NGN / ha · zero allowed</span></label><div className="cost-grid">{COST_CATEGORIES.map((key) => <label key={key}><span>{labels[key]}</span><input aria-label={labels[key]} type="number" min="0" value={active.costsPerHa[key]} onChange={(e) => updateCost(activeCrop, key, e.target.value)} /></label>)}</div></div></div>}</section>
      {ready && <section className="print-report"><h2>Fieldmargin scenario report</h2><p>Generated {new Date().toLocaleString()} · ranking basis: estimated net profit from your scenario prices.</p>{batch.results.map((r) => <div key={r.crop.crop_id}><h3>{r.crop.name} ({r.crop.form})</h3><p>Area: {r.assumptions.areaHa} ha · Yield: {r.assumptions.yieldTPerHa} t/ha · Selling price: {money(r.assumptions.sellingPriceNgnPerKg)}/kg</p><p>Price basis: {priceLabel(draftFor(r.crop.crop_id))}{draftFor(r.crop.crop_id).priceSuggestion ? ` · observation ${draftFor(r.crop.crop_id).priceSuggestion!.observationDate} · ${draftFor(r.crop.crop_id).priceSuggestion!.sourceAttribution}` : ''}</p><p>{money(r.profit)} net profit · {money(r.revenue)} revenue · {money(r.totalCost)} total cost</p><p>Price range: {r.assumptions.priceRangeNgnPerKg ? `${money(r.assumptions.priceRangeNgnPerKg.low)}–${money(r.assumptions.priceRangeNgnPerKg.high)}/kg` : 'not entered'}</p><p>Costs/ha: {COST_CATEGORIES.map((key) => `${labels[key]} ${money(r.assumptions.costsPerHa[key])}`).join(' · ')}</p></div>)}<p>Disclaimer: These are user-entered scenarios, not forecasts, confidence intervals, or guarantees.</p></section>}
    </main><footer><span>fieldmargin · offline crop planning for Nigeria</span><span>Calculator-only fallback</span></footer></div>
}
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`).catch(() => undefined))
